/*
Even Fibonacci numbers

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

void solution() {
	int total, final_term, term_1, term_2;
	total = 0;
	term_1 = 1;
	term_2 = 1;
	while(final_term < 4000000) {
		final_term = term_1 + term_2;
		if(final_term % 2 == 0) {
			total += final_term;
		}
		term_1 = term_2;
		term_2 = final_term;
	}

	printf("\n\t\tThe sum of even fibonacci until 4 millon is = %d\n", total);
}

int main(int argc, char **argv) {
	printf("\nEven Fibonacci numbers\n");
	printf("\n\tEach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:");
	printf("\n\t\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
	printf("\n\tBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
	solution();
	return 0;
}
// solved by W1N3

