#!/bin/bash

i=$1
sl=$2
key_seq=( "$@" )
unset 'key_seq[0]'
unset 'key_seq[1]'
while [ "$i" -ne 0 ] # loop in the first argument - number of repetitions
do
	sleep "$sl"
	for k in "${key_seq[@]}" # loop in the list of arguments - sequence of keystrokes
	do
		xdotool key --delay 200 $k
	done
	i=$(($i-1))
done
exit 0

